services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: Spring
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

#  mySQL:
#    image: mysql:5.7
#    restart: unless-stopped
#    environment:
#      #      MYSQL_USER : root
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: order
#    ports:
#      - 3307:3306
#    volumes:
#      - db:/var/lib/mysql
#  adminer:
#    image: adminer
#    restart: unless-stopped
#    ports:
#      - 80:8080
#  keycloack:
#    image: jboss/keycloak
#    ports:
#      - 9090:8080
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
#  db:
