spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product
          uri: lb://product
          predicates:
            - Path=/api/v1/product
        - id: order
          uri: lb://order
          predicates:
            - Path=/api/v1/order/**
        - id: inventory
          uri: lb://inventory
          predicates:
            - Path=/api/v1/inventory/**
        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: eureka-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/shopmicroservices


server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka