spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product
          uri: lb://product
          predicates:
            - Path=/api/v1/product
        - id: order
          uri: lb://order
          predicates:
            - Path=/api/v1/order/**
        - id: inventory
          uri: lb://inventory
          predicates:
            - Path=/api/v1/inventory/**


server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka